# Generated by Django 3.2.9 on 2021-11-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
