# Generated by Django 3.2.9 on 2021-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0002_rename_released_date_release_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('tag_name', models.CharField(max_length=120)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('published_at', models.DateField()),
                ('tag_name', models.CharField(max_length=120)),
                ('image', models.URLField()),
                ('host_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=120)),
                ('picture', models.URLField()),
                ('author', models.CharField(max_length=120)),
                ('tag_name', models.CharField(max_length=120)),
            ],
        ),
    ]
