# Generated by Django 3.2.9 on 2021-11-22 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0003_article_podcast_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 9, 59, 26, 436221)),
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 9, 59, 26, 436904)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 9, 59, 26, 435951)),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 9, 59, 26, 435696)),
        ),
    ]
