# Generated by Django 3.2.9 on 2021-11-22 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0004_auto_20211122_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 0, 35, 124576)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 0, 35, 124292)),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 0, 35, 124042)),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 0, 35, 124816)),
        ),
    ]
