# Generated by Django 3.2.9 on 2021-11-22 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0006_auto_20211122_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 6, 56, 964776)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 6, 56, 964509)),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 6, 56, 964252)),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 10, 6, 56, 965012)),
        ),
    ]
