# Generated by Django 3.2.9 on 2021-11-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0008_auto_20211122_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 11, 15, 10, 521961)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 11, 15, 10, 521689)),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 11, 15, 10, 521434)),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 11, 15, 10, 522203)),
        ),
    ]
