# Generated by Django 3.2.9 on 2021-11-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hack4Music', '0011_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default='2021-11-23'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published_at',
            field=models.DateField(default='2021-11-23'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default='2021-11-23'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateField(default='2021-11-23'),
        ),
    ]
